/**
 * @param {{
 *   exportId: string
 *   manifestId: string
 *   ruleSnapshotId: string
 *   sourceEntryCount: number
 *   evidenceCount: number
 *   exceptionCount: number
 *   waivedCount: number
 *   generatedBy: string
 *   generatedAt: string
 }} props
 */
export default function ManifestReferenceCard({
  exportId,
  manifestId,
  ruleSnapshotId,
  sourceEntryCount,
  evidenceCount,
  exceptionCount,
  waivedCount,
  generatedBy,
  generatedAt,
}) {
  return (
    <div className="card">
      <div className="label">Manifest Reference</div>
      <p className="small">
        <strong>Export:</strong> <span className="code">{exportId}</span>
      </p>
      <p className="small">
        <strong>Manifest:</strong> <span className="code">{manifestId}</span>
      </p>
      <p className="small">
        <strong>Rule snapshot:</strong> <span className="code">{ruleSnapshotId}</span>
      </p>
      <p className="small">
        Sources: {sourceEntryCount} · Evidence: {evidenceCount} · Exceptions: {exceptionCount} ·
        Waived: {waivedCount}
      </p>
      <p className="small">
        Generated by {generatedBy} at {generatedAt}
      </p>
    </div>
  );
}

