export const queryKeys = {
  projects: () => ["projects"],
  sourceRecords: () => ["source_records"],
  runs: () => ["runs"],
  issues: () => ["issues"],
  exports: () => ["exports"],
  manifests: () => ["manifests"],
  dashboardPortfolio: () => ["dashboard", "portfolio"],
  dashboardProject: () => ["dashboard", "project"],
  dashboardOps: () => ["dashboard", "inspection_ops"],
  dashboardCompliance: () => ["dashboard", "compliance"],
  dashboardMyWork: () => ["dashboard", "my_work"],
  dashboardExportCenter: () => ["dashboard", "export_center"],
  dashboardSourceFreshness: () => ["dashboard", "source_freshness"],
  dashboardPortfolioDrilldowns: () => ["dashboard", "portfolio_drilldowns"],
  projectsWorkspace: () => ["projects", "workspace"],
  projectWorkspace: (projectId) => ["projects", projectId, "workspace"],
  inspectionsList: (filters = {}) => ["inspections", "list", filters],
  inspectionsReviewQueue: () => ["inspections", "review_queue"],
  inspectionsRecurring: () => ["inspections", "recurring"],
  issuesList: (filters = {}) => ["issues", "list", filters],
  issuesOverdue: () => ["issues", "overdue"],
  issuesVerification: () => ["issues", "verification"],
  issueDetail: (issueId) => ["issues", issueId],
  templatesFamilies: () => ["templates", "families"],
  templateFamilyDetail: (templateFamilyId) => ["templates", templateFamilyId],
  templateVersionDetail: (templateVersionId) => ["templates", "versions", templateVersionId],
  rulesPacket: () => ["rules", "packet"],
  rulesCadence: () => ["rules", "cadence"],
  rulesSnapshots: () => ["rules", "snapshots"],
  rulesPreviews: () => ["rules", "previews"],
  adminOverview: () => ["admin", "overview"],
  auditEvents: () => ["audit_events"],
  vaultSlots: (projectId) => ["vault_slots", projectId]
};
